
# README
This document was generated by Gadget by providing a valid [Go template](./README.tpl). You can generate this document yourself by running the following in the `/sink` directory:
```bash
$ gadget --format template --template README.tpl
```
Or, without the `--template ...` flag as it will use `README.tpl` as the default template:
```
$ gadget --format template
```
Enjoy!
{{ range . }}
# Package `{{ .Name }}`
{{ range .Files.Items }}
## File `{{ .Name }}` {{ $path := .Name }}{{ range .Functions.Items }}
### Function `{{ .Name }}`
* `{{ trim .Signature }}` [#]({{ $path }}#L{{ .LineStart }})
* `{{ $path }}:{{ .LineStart }}:{{ .LineEnd }}` [#]({{ $path }}#L{{ .LineStart }}-L{{ .LineEnd }})

{{ if .Doc }}{{ .Doc | replace "\n" "" }}{{ end }}
{{ if .Body }}
```go
{{ .Body }}
```
{{ end }}{{ end }}{{ end }}{{ end }}